version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./CRUD_application_NestJS_PostgreSQL_Docker
    volumes:
      - ./CRUD_application_NestJS_PostgreSQL_Docker:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db

  postgres: 
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

